[workspace]
authors = ["Adolfo Ochagav√≠a <github@adolfo.ochagavia.nl>"]
channels = ["conda-forge"]
name = "cli"
platforms = [
    "linux-64",
    "linux-aarch64",
    "osx-arm64",
    "osx-64",
    "win-64",
]
version = "0.1.0"

[tasks]

[dependencies]

[target.win-64.dependencies]
vs2022_win-64 = ">=19.44.35207,<20"
