[workspace]
authors = ["Adolfo Ochagav√≠a <github@adolfo.ochagavia.nl>"]
channels = ["conda-forge"]
name = "lib-rust"
platforms = [
    "linux-64",
    "linux-aarch64",
    "osx-arm64",
    "osx-64",
    "win-64",
]
# [[kson-version-num]]
version = "0.3.0-dev"

[tasks]

[dependencies]
rust = "1.89.0.*"

[target.win-64.dependencies]
vs2022_win-64 = ">=19.44.35207,<20"

[target.linux-64.dependencies]
libclang = "20.*"
sysroot_linux-64 = ">=2.34"
zlib = "==1.3.1"

[target.linux-64.activation.env]
LIBCLANG_PATH = "$CONDA_PREFIX/lib"

[target.linux-aarch64.dependencies]
libclang = "20.*"
sysroot_linux-64 = ">=2.34"
zlib = "==1.3.1"

[target.linux-aarch64.activation.env]
LIBCLANG_PATH = "$CONDA_PREFIX/lib"
